中文="good"
print(中文)
print("9/2=",9/2)
print("9//2=",9//2)
print("2*2=",2*2)
print("2**3=",2**3)
name="黑马程序员'"
print('黑马程序⚪"')
print("\"黑马程序⚪")
addres='a'
add1=12.233
addsum="今天来了%s,没来%f"%(addres,add1)
print(addres,add1)
print(addsum)
print("数字%f限制宽度7，小数保留2的结果为:%7.2f"%(add1,add1))
ball="篮球"
sing="唱"
jump="跳"
rap="rap"
music="music"
print(f"我喜欢{sing},{jump},{rap},{ball},{music}!")

